<?php
require_once dirname(dirname(__FILE__))."/configGlobal.php";

//DIRECTORIOS RELATIVOS NO PHP
define ('DIR_LOCAL_CSS_SEGUIMIENTO_DESPACHO',DIR_REL_SEGUIMIENTO_DESPACHO."css/");
define ('DIR_LOCAL_IMG_SEGUIMIENTO_DESPACHO',DIR_REL_SEGUIMIENTO_DESPACHO."img/");
define ('DIR_LOCAL_JS_SEGUIMIENTO_DESPACHO',DIR_REL_SEGUIMIENTO_DESPACHO."js/");
//DIRECTORIOS RELATIVOS PHP
define ('DIR_LOCAL_SRC_SEGUIMIENTO_DESPACHO',DIR_ABS_SEGUIMIENTO_DESPACHO."src/");
define ('DIR_LOCAL_RESPONSABLE_SEGUIMIENTO_DESPACHO',DIR_REL_SEGUIMIENTO_DESPACHO."src/contenido/responsable/");
define ('DIR_LOCAL_DATAGRID_SEGUIMIENTO_DESPACHO',DIR_REL_SEGUIMIENTO_DESPACHO."src/contenido/datagrid/");
?>